# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('simulated-annealing', [
        'core', 'internet', 'network', 'applications', 'mesh', 'mobility', 'olsr', 'wifi', 'propagation', 'mesh-sim'])
    module.source = [
        'model/simulated-annealing.cc',
        'helper/simulated-annealing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('simulated-annealing')
    module_test.source = [
        'test/simulated-annealing-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/simulated-annealing-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'simulated-annealing'
    headers.source = [
        'model/simulated-annealing.h',
        'helper/simulated-annealing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

